"""empty message

Revision ID: 7cd041ffb65b
Revises: 
Create Date: 2018-07-28 09:54:00.919145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd041ffb65b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=64), nullable=False),
    sa.Column('leading_actor', sa.String(length=64), nullable=False),
    sa.Column('show_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('m_id'),
    sa.UniqueConstraint('m_name')
    )
    op.create_table('person',
    sa.Column('p_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('person_movie',
    sa.Column('pm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('m_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['m_id'], ['movies.m_id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['person.p_id'], ),
    sa.PrimaryKeyConstraint('pm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_movie')
    op.drop_table('person')
    op.drop_table('movies')
    # ### end Alembic commands ###
